version: "3.6"

services: # docker-compose up web database redis sidekiq
  web:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && /app/bin/dev"
    restart: always
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    links:
      - "database"
      - "redis"
    env_file:
      - ".env"
  database:
    image: postgres:latest
    restart: always
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - "5432"
    env_file:
      - ".env"
  redis:
    image: redis:latest
    restart: always
    volumes:
      - "redis:/data"
    ports:
      - "6379"
  sidekiq:
    depends_on:
      - "database"
      - "redis"
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: "bundle exec sidekiq"
    restart: always
    volumes:
      - ".:/app"
      - "/app/tmp" # don't mount tmp dir
    env_file:
      - ".env"
  chrome: # docker-compose up -d chrome
    image: browserless/chrome:latest # See https://www.browserless.io/docs/docker
    ports:
      - "3333:3333"
    environment:
      PORT: 3333
      CONNECTION_TIMEOUT: -1 # No timeout

volumes:
  redis:
  postgres:
