# fly.toml app configuration file generated for cold-dream-5563 on 2023-05-09T14:08:57-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cold-dream-5563"
primary_region = "ord"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
